import { Venture } from "./src/types/models";
import bg2 from "./src/assets/bg2.png";

export const data: Venture[] = [
  {
    id: "1",
    name: "Inself",
    description: "",
    v_token_amount: 2000,
    image_url: "",
    created_at: new Date().toISOString(),
    end_date: new Date().toISOString(),
    category: "",
    members: [
      {
        id: "1",
        name: "Ronen Gafni",
        email: "ronen@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "2",
        name: "Adi Carmon Scope",
        email: "adi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "3",
        name: "Moran Horovitz Pahima",
        email: "moran@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
    ],
  },
  {
    id: "1",
    name: "Inself",
    description: "",
    v_token_amount: 2000,
    image_url: bg2,
    created_at: new Date().toISOString(),
    end_date: new Date().toISOString(),
    category: "",
    members: [
      {
        id: "1",
        name: "Ronen Gafni",
        email: "ronen@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "2",
        name: "Adi Carmon Scope",
        email: "adi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "3",
        name: "Moran Horovitz Pahima",
        email: "moran@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
    ],
  },
  {
    id: "1",
    name: "Inself",
    description: "",
    v_token_amount: 2000,
    image_url: bg2,
    created_at: new Date().toISOString(),
    end_date: new Date().toISOString(),
    category: "",
    members: [
      {
        id: "1",
        name: "Ronen Gafni",
        email: "ronen@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "2",
        name: "Adi Carmon Scope",
        email: "adi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "3",
        name: "Moran Horovitz Pahima",
        email: "moran@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
    ],
  },
  {
    id: "1",
    name: "Inself",
    description: "",
    v_token_amount: 2000,
    image_url: "",
    created_at: new Date().toISOString(),
    end_date: new Date().toISOString(),
    category: "",
    members: [
      {
        id: "1",
        name: "Ronen Gafni",
        email: "ronen@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "2",
        name: "Adi Carmon Scope",
        email: "adi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "3",
        name: "Moran Horovitz Pahima",
        email: "moran@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
    ],
  },
  {
    id: "1",
    name: "Inself",
    description: "",
    v_token_amount: 2000,
    image_url: "",
    created_at: new Date().toISOString(),
    end_date: new Date().toISOString(),
    category: "",
    members: [
      {
        id: "1",
        name: "Ronen Gafni",
        email: "ronen@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "2",
        name: "Adi Carmon Scope",
        email: "adi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "3",
        name: "Moran Horovitz Pahima",
        email: "moran@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
    ],
  },
  {
    id: "1",
    name: "Inself",
    description: "",
    v_token_amount: 2000,
    image_url: "",
    created_at: new Date().toISOString(),
    end_date: new Date().toISOString(),
    category: "",
    members: [
      {
        id: "1",
        name: "Ronen Gafni",
        email: "ronen@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "2",
        name: "Adi Carmon Scope",
        email: "adi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "3",
        name: "Moran Horovitz Pahima",
        email: "moran@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
      {
        id: "4",
        name: "Noi Gafni",
        email: "noi@gmail.com",
        image_url: "",
        created_at: new Date().toISOString(),
        role: "superuser",
      },
    ],
  },
];

export const user = {
  id: "1",
  name: "Ronen Gafni",
  email: "ronen@gmail.com",
  image_url: "",
  created_at: new Date().toISOString(),
  role: "superuser",
};

export const studio = {
  backgroundColor: "#f2ebdb",
  studioName: "#4d4d4d",
  topBarColor: "#f2ebdb",
  isSidebarCollapsed: false,
  toggleSidebar: () => {},
  sidebarColor: "#f2ebdb",
  setStudioName: (val: string) => {},
  setBackgroundColor: (val: string) => {},
  setTopBarColor: (val: string) => {},
  setSidebarColor: (val: string) => {},
};
